import logging
from logging.handlers import TimedRotatingFileHandler


class Logger:
    def __init__(self):
        self.log_path = "log"

        self.logger = logging.getLogger("GmailReader")
        self.logger.setLevel(logging.INFO)
        self.formatter = logging.Formatter('%(levelname)s - %(asctime)s - %(name)s - %(funcName)s | %(message)s')

        ch = logging.StreamHandler()
        ch.setLevel(logging.DEBUG)
        ch.setFormatter(self.formatter)
        self.logger.addHandler(ch)

        handler = TimedRotatingFileHandler(self.log_path, when="d", interval=1, backupCount=5)
        handler.setFormatter(self.formatter)
        self.logger.addHandler(handler)

        aps_logger = logging.getLogger('apscheduler.scheduler')
        aps_logger.addHandler(handler)
        aps_logger.addHandler(ch)
        aps_logger.setLevel(logging.DEBUG)

    def info(self, logstr):
        self.logger.info(logstr)

    def log(self, logstr):
        self.logger.log(logstr)

    def debug(self, logstr):
        self.logger.debug(logstr)

    def error(self, logstr):
        self.logger.error(logstr)

    def exception(self, e):
        self.logger.exception(e)




ERROR - 2022-10-14 16:52:11,180 - GmailReader - error | (psycopg2.OperationalError) connection to server at "database-2.ccknekyc13f2.ap-south-1.rds.amazonaws.com" (10.120.21.231), port 5432 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8) <class 'sqlalchemy.exc.OperationalError'> database.py, Line 27
